Handle cases where temperatures cannot be read

diff --git a/ipmi b/ipmi
--- a/ipmi
+++ b/ipmi
@@ -23,6 +23,9 @@ trap "kill 0" EXIT
 
 adjust() {
     local temp="$(get_temp)"
+    if [ ! "${temp-}" ]; then
+        echo "Could not read temperatures" >&2
+    fi
     if [ "$temp" -lt "$LAST_TEMP" ]; then
         TEMP_DECREASING=1
         TEMP_INCREASING=
